services:
  - type: web
    name: my-springboot-app
    env: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-db-url
